org: antoniocot
service: api-solicitud-prestamo

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::316129865556:role/LabRole
  environment:
    SOLICITUD_PRESTAMO_TABLE: TABLA-SOLICITUD-PRESTAMO

functions:
  crearSolicitudPrestamo:
    handler: crearSolicitudPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/crear
          method: post
          cors: true
          integration: lambda
          
  listarSolicitudesPrestamo:
    handler: listarSolicitudesPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/listar
          method: post
          cors: true
          integration: lambda
          
  aceptarSolicitudPrestamo:
    handler: aceptarSolicitudPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/aceptar
          method: post
          cors: true
          integration: lambda
          
  rechazarSolicitudPrestamo:
    handler: rechazarSolicitudPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/rechazar
          method: post
          cors: true

  obtenerSolicitudPrestamo:
    handler: obtenerSolicitudPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/obtener
          method: post
          cors: true
          integration: lambda
          
  listarPorEstado:
    handler: filtrarPorEstado.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/listar-estado
          method: post
          cors: true
          integration: lambda
          
  eliminarSolicitudPrestamo:
    handler: eliminarSolicitudPrestamo.lambda_handler
    events:
      - http:
          path: /solicitud-prestamo/eliminar
          method: delete
          cors: true
          integration: lambda
          
resources:
  Resources:
    SolicitudPrestamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SOLICITUD_PRESTAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
          - AttributeName: solicitud_id
            AttributeType: S
          - AttributeName: estado
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
          - AttributeName: solicitud_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true        
        GlobalSecondaryIndexes:
          - IndexName: EstadoIndex
            KeySchema:
              - AttributeName: estado
                KeyType: HASH
              - AttributeName: solicitud_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
